### ISSUE TITLE
Implement Dwellberry cultivation

### ISSUE THREAD

**Issue by BitTim** [TheBluebits/Project-Hong-Taiyang#24]
Implement the following:
- [x] Make Dwellberry Seeds placeable on Darkdweller Logs, like Cocoa on Jungle Logs
- [x] Make the Dwellberries grow
- [x] Drop single seed when broken before fully grown
- [x] Drop fruit and seeds when broken and fully grown
- [x] Make dwellberries edible according to notion

Some aspects are dependant on #25

**Comment by TheCrazyshine** [comment]
It's ya boi

**Comment by BitTim** [comment]
Merged with #28
